b_timetable = tk.Button(leftFrame, command=callTimeTable)
    b_timetable.place(relx=0.019, rely=0.099, height=34, width=187)
    b_timetable.configure(activebackground="#9d004f")
    b_timetable.configure(activeforeground="white")
    b_timetable.configure(activeforeground="#ffffff")
    b_timetable.configure(background="#ae0057")
    b_timetable.configure(disabledforeground="#a3a3a3")
    b_timetable.configure(font="-family {Segoe UI Black} -size 11 -weight bold")
    b_timetable.configure(foreground="#ffffff")
    b_timetable.configure(highlightbackground="#d9d9d9")
    b_timetable.configure(highlightcolor="black")
    b_timetable.configure(pady="0")
    b_timetable.configure(text='''Timetable''')

    b_notice = tk.Button(leftFrame, command=callNotices)
    b_notice.place(relx=0.019, rely=0.198, height=34, width=187)
    b_notice.configure(activebackground="#9d004f")
    b_notice.configure(activeforeground="white")
    b_notice.configure(activeforeground="#ffffff")
    b_notice.configure(background="#ae0057")
    b_notice.configure(disabledforeground="#a3a3a3")
    b_notice.configure(font="-family {Segoe UI Black} -size 11 -weight bold")
    b_notice.configure(foreground="#ffffff")
    b_notice.configure(highlightbackground="#d9d9d9")
    b_notice.configure(highlightcolor="black")
    b_notice.configure(pady="0")
    b_notice.configure(text='''Notice''')

    b_notes = tk.Button(leftFrame, command=showNotes)
    b_notes.place(relx=0.019, rely=0.296, height=34, width=187)
    b_notes.configure(activebackground="#9d004f")
    b_notes.configure(activeforeground="white")
    b_notes.configure(activeforeground="#ffffff")
    b_notes.configure(background="#ae0057")
    b_notes.configure(disabledforeground="#a3a3a3")
    b_notes.configure(font="-family {Segoe UI Black} -size 11 -weight bold")
    b_notes.configure(foreground="#ffffff")
    b_notes.configure(highlightbackground="#d9d9d9")
    b_notes.configure(highlightcolor="black")
    b_notes.configure(pady="0")
    b_notes.configure(text='''Notes''')

    b_contacts = tk.Button(leftFrame, command=callContacts)
    b_contacts.place(relx=0.019, rely=0.395, height=34, width=187)
    b_contacts.configure(activebackground="#9d004f")
    b_contacts.configure(activeforeground="white")
    b_contacts.configure(activeforeground="#ffffff")
    b_contacts.configure(background="#ae0057")
    b_contacts.configure(disabledforeground="#a3a3a3")
    b_contacts.configure(font="-family {Segoe UI Black} -size 11 -weight bold")
    b_contacts.configure(foreground="#ffffff")
    b_contacts.configure(highlightbackground="#d9d9d9")
    b_contacts.configure(highlightcolor="black")
    b_contacts.configure(pady="0")
    b_contacts.configure(text='''Contacts''')

    b_marks = tk.Button(leftFrame, command=callMarks)
    b_marks.place(relx=0.019, rely=0.494, height=34, width=187)
    b_marks.configure(activebackground="#9d004f")
    b_marks.configure(activeforeground="white")
    b_marks.configure(activeforeground="#ffffff")
    b_marks.configure(background="#ae0057")
    b_marks.configure(disabledforeground="#a3a3a3")
    b_marks.configure(font="-family {Segoe UI Black} -size 11 -weight bold")
    b_marks.configure(foreground="#ffffff")
    b_marks.configure(highlightbackground="#d9d9d9")
    b_marks.configure(highlightcolor="black")
    b_marks.configure(pady="0")
    b_marks.configure(text='''Marks''')

    b_assignments = tk.Button(leftFrame, command=callAssignments)
    b_assignments.place(relx=0.019, rely=0.593, height=34, width=187)
    b_assignments.configure(activebackground="#9d004f")
    b_assignments.configure(activeforeground="white")
    b_assignments.configure(activeforeground="#ffffff")
    b_assignments.configure(background="#ae0057")
    b_assignments.configure(disabledforeground="#a3a3a3")
    b_assignments.configure(font="-family {Segoe UI Black} -size 11 -weight bold")
    b_assignments.configure(foreground="#ffffff")
    b_assignments.configure(highlightbackground="#d9d9d9")
    b_assignments.configure(highlightcolor="black")
    b_assignments.configure(pady="0")
    b_assignments.configure(text='''Assignments''')